# Setup
title:       分享技术 品味生活
tagline:   talk is cheap, show me the code
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Author mingliang
  url:        l.ming@huawei.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
theme: jekyll-theme-cayman